language:
  node_js
node_js:
  - 12
before_install:
  - npm install
script:
  - npm run test
cache:
  directories:
    - node_modules
notifications:
  email:
    recipients:
      - zhangchi3@outlook.com
    on_success: always # default: change
    on_failure: always # default: always